Android: make sure we set the correct minimum API
Do this by appending it to the LLVM triple. While there, make
sure we use the same logic for setting the API. While there
introduce code for guessing the NDK_ROOT.

diff --git a/cross-android b/cross-android
--- a/cross-android
+++ b/cross-android
@@ -20,6 +20,15 @@ export ANDROID_TOOLCHAIN=${ROOTDIR}/MK_BUILD/toolchain/android/${ARCH}
 # Directory under the toolchain where we have headers and libs
 export SYSROOT=${ANDROID_TOOLCHAIN}/sysroot
 
+# We need to know the minimum API number to enforce the minimum by
+# appending to the LLVM_TRIPLE below. Otherwise, we will compile
+# objects targeting the latest available android API.
+export API=`./config-android-api $ARCH`
+if [ "$API" = "" ]; then
+  echo "FATAL: unable to determine the API for $ARCH" 1>&2
+  exit 1
+fi
+
 #
 # Map the selected architecture to useful variables:
 #
@@ -32,6 +41,7 @@ if [ "$ARCH" = "arm64" ]; then
   # Note: arm64 is also known as aarch64 and as armv8
   TOOLCHAIN_NAME=aarch64-linux-android
   DESTDIR_NAME=arm64-v8a
+  ANDROID_ARCH_FLAGS="-target aarch64-none-linux-android$API"
 elif [ "$ARCH" = "armeabi-v7a" ]; then
   TOOLCHAIN_NAME=arm-linux-androideabi
   DESTDIR_NAME=$ARCH
@@ -39,14 +49,16 @@ elif [ "$ARCH" = "armeabi-v7a" ]; then
   # <Bandwagon>These flags have been copied from the flags used by
   # ndk-build when building measurement-kit as a C++ library</>.
   #
-  ANDROID_ARCH_FLAGS="-target armv7-none-linux-androideabi -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -mthumb"
+  ANDROID_ARCH_FLAGS="-target armv7-none-linux-androideabi$API -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -mthumb"
 elif [ "$ARCH" = "x86" ]; then
   TOOLCHAIN_NAME=i686-linux-android
   DESTDIR_NAME=x86
+  ANDROID_ARCH_FLAGS="-target i686-none-linux-android$API"
 elif [ "$ARCH" = "x86_64" ]; then
   TOOLCHAIN_NAME=x86_64-linux-android
   DESTDIR_NAME=x86_64
   LIB_SUFFIX=64
+  ANDROID_ARCH_FLAGS="-target x86_64-none-linux-android$API"
 else
   echo "$0: invalid $ARCH" 1>&2
   exit 1
diff --git a/toolchain-android b/toolchain-android
--- a/toolchain-android
+++ b/toolchain-android
@@ -8,12 +8,14 @@ if [ $# -ne 1 ]; then
   echo "" 1>&2
   exit 1
 fi
+
+ROOTDIR=$(cd $(dirname $0) && pwd -P)
+export NDK_ROOT=`$ROOTDIR/config-android-ndk-root`
 if [ "$NDK_ROOT" = "" ]; then
-  echo "FATAL: you must set NDK_ROOT" 1>&2
+  echo "FATAL: unable to determine NDK_ROOT; please export NDK_ROOT=/path." 1>&2
   exit 1
 fi
 
-ROOTDIR=$(cd $(dirname $0) && pwd -P)
 ARCH=$1
 shift
 BASEDIR=$ROOTDIR/MK_BUILD/toolchain/android
@@ -27,11 +29,10 @@ if [ "$ARCH" = "armeabi-v7a" ]; then
   ARCH="arm"
 fi
 
-# See https://github.com/measurement-kit/measurement-kit/pull/1554#discussion_r167493143
-if [ "$ARCH" = "arm64" -o "$ARCH" = "mips64" -o "$ARCH" = "x86_64" ]; then
-  API=21
-else
-  API=16
+API=`$ROOTDIR/config-android-api $ARCH`
+if [ "$API" = "" ]; then
+  echo "FATAL: unable to determine API for $ARCH" 1>&2
+  exit 1
 fi
 
 MAKE_TOOLCHAIN=${NDK_ROOT}/build/tools/make_standalone_toolchain.py
